# Generated by Django 2.2.16 on 2020-10-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_tytryrytrytr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='tytryrytrytr',
        ),
    ]
