# Generated by Django 2.2.16 on 2020-10-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customtext_tytryrytrytr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='fgdgd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
