# Generated by Django 2.2.16 on 2020-10-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customtext_fgdgd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='fgdgd',
        ),
    ]
