# Generated by Django 2.2.16 on 2020-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customtext_fgdgd'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='titlef',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
