# Generated by Django 2.2.16 on 2020-10-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_customtext_fgdgd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testjhjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgfghfhfhgfh', models.BigIntegerField()),
            ],
        ),
    ]
