# Generated by Django 2.2.16 on 2020-10-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_testjhjh'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='jhgjhghjgfjhjg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
