# Generated by Django 2.2.16 on 2020-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customtext_jhgjhghjgfjhjg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hghgjhgj',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
