# Generated by Django 2.2.16 on 2020-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_customtext_hghgjhgj"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="hgfjhghgkjjhg",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
