# Generated by Django 2.2.16 on 2020-10-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customtext_hgfjhghgkjjhg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='hgfjhghgkjjhg',
            new_name='hjgfjgjfgjgjghfjhf',
        ),
    ]
