# Generated by Django 2.2.16 on 2020-10-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201019_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hghgjhgj',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hjgfjgjfgjgjghfjhf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhghjgfjhjg',
        ),
    ]
